In [1]:
'''
    Name: Le Hoang Duc
    Student ID: 18110075
    ML - Lab01
'''
import numpy as np 
import pandas as pd

In [2]:
from sklearn import datasets
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)
diabetes_X_train,diabetes_y_train=diabetes_X[:-2],diabetes_y[:-2].reshape(1,-1).T
diabetes_X_test,diabetes_y_test=diabetes_X[-2:],diabetes_y[-2:].reshape(1,-1).T

In [3]:
X_train = diabetes_X_train
y_train = diabetes_y_train

In [4]:
print(X_train.shape)
print(y_train.shape)

(440, 10)
(440, 1)


In [5]:
one = np.ones((X_train.shape[0], 1))
Xbar = np.concatenate((one, X_train), axis = 1)

In [6]:
print(Xbar.shape)

(440, 11)


In [7]:
print(Xbar)

[[ 1.          0.03807591  0.05068012 ... -0.00259226  0.01990842
  -0.01764613]
 [ 1.         -0.00188202 -0.04464164 ... -0.03949338 -0.06832974
  -0.09220405]
 [ 1.          0.08529891  0.05068012 ... -0.00259226  0.00286377
  -0.02593034]
 ...
 [ 1.          0.04170844  0.05068012 ... -0.00259226  0.03119299
   0.00720652]
 [ 1.         -0.00551455  0.05068012 ...  0.03430886 -0.01811827
   0.04448548]
 [ 1.          0.04170844  0.05068012 ... -0.01107952 -0.04687948
   0.01549073]]


In [8]:
A = np.dot(Xbar.T, Xbar)
b = np.dot(Xbar.T, y_train)
w = np.dot(np.linalg.pinv(A), b)

In [9]:
print('Coefficents: \n', w[1:])
print('Intercept: \n', w[0])

Coefficents: 
 [[  -9.38654069]
 [-239.50541995]
 [ 519.71747928]
 [ 324.62241148]
 [-788.75647584]
 [ 474.10341796]
 [  98.46801188]
 [ 175.8004285 ]
 [ 749.38200399]
 [  67.88567794]]
Intercept: 
 [152.10620412]


In [10]:
X_test = diabetes_X_test
y_test = diabetes_y_test
print(X_test.shape)
print(y_test.shape)

(2, 10)
(2, 1)


In [11]:
one = np.ones((X_test.shape[0], 1))
Xbar_test = np.concatenate((one, X_test), axis = 1)

In [12]:
pred = Xbar_test.dot(w)
print(pred)
print(y_test)

[[211.74929866]
 [ 53.19292183]]
[[220.]
 [ 57.]]


In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)
models_pred = model.predict(X_test)

print('Coefficients: \n', model.coef_)
print('Intercept: \n', model.intercept_)

print(f'Mean squared error: {mean_squared_error(models_pred, y_test)}')


Coefficients: 
 [[  -9.38654069 -239.50541995  519.71747928  324.62241148 -788.75647584
   474.10341796   98.46801188  175.8004285   749.38200399   67.88567794]]
Intercept: 
 [152.10620412]
Mean squared error: 41.283958422945254
